use test;
drop table IF EXISTS TB_USERSS;
create table TB_USERSS(ID INT AUTO_INCREMENT, ID_RESOURCE VARCHAR(40), PRIMARY KEY (ID));
drop table IF EXISTS TB_USERSS_REGION;
create table TB_USERSS_REGION(ID INT AUTO_INCREMENT, COUNTRY VARCHAR(40), REGION VARCHAR(40), CITY VARCHAR(40), PRIMARY KEY (ID));

-- copy and paste on mysqlconsole
